unique_ids:
  assets:
    faq.css: '1744196986867520335294180.58777'
    images/.gitkeep: '174234953718744733406316.02895'
    images/app-store.png: '1742349585633672666405751.7937'
    images/bullet.svg: '174234961120755952051317.65923'
    images/choose-bg.png: G6CALLU6E2BUV3P2JBWYMLD7VHTE66CX
    images/cta-bg.png: KYSFQEMM2RM3JGQI3J7UVL7N3XFQCM6P
    images/customer.png: KLFHASCHZXOCZYG7OGXH7C3ZLQ4KOK5S
    images/download.svg: YKKGF27G7VN7EL6DKZCT43UOQEUHZWAI
    images/dropdown-arrow.svg: HTEAUATPY364K2W6STQR7RJQIMDL7H7R
    images/facebook.svg: YKYLQVJC23IACOCL33WR6ATIV6Z2BRQH
    images/flower.svg: KRTTDSGSBRJRWS4FNAEM2WYFCIAN2KVE
    images/footer-bg.png: LTJU4WTUATRPX4TXNG6ENIDXVQWBUXYQ
    images/get-device.png: WWAKNCZWXLNIMM3G2JXLSBMTJ5SDPWRN
    images/get-started-bg.png: H6CN7IVBV33Q7435RKHIFWBQRTE2YW4I
    images/google.svg: RSWEVRMZ4IJW6YLQQYIKFWHVHPZXG5Z5
    images/guide-bg.png: 4OX6CK4HU3EMVWAVQIKFHYO4SEODX2JX
    images/hero-bg.png: 3GYTB4SLGMP55ZQRMY552KGZVE6IB6JQ
    images/instagram.svg: RVU2K3Z3MHFHN5Q7LIOCI4K35K3FP5JZ
    images/iphone-img.png: 5JJ4WUHSGTRG5BDFQTPR67MOMCHOF4J4
    images/logo.png: JKCXV4LE336TS6IHZG6X5BKP4RCA5IF4
    images/play-store.png: YTIEA3PYKI6YOUCTJEWHUOL74ORYREWO
    images/plus-button.svg: VBZ6AIIDOXUZ5PW6ATILMCUOH47WGPBE
    images/rating.png: LMYDYVJAN5DC4OJH7R4DUAXFVOC4QOV6
    images/right-arrow.svg: 6ZMEXIN7KHJOVDP4YLG4IAVGQHXN33YA
    images/services-bg.png: U7F53FKD7T3DDHGSQKN6YVK6YF5R4FGE
    images/setting-button.svg: SFRXN3LIAKOEBBNDXDAE53LKWWT4NDYX
    images/sign-up.svg: ILHEVNNRMBFPSNOB6GAWUA5STXV5ZRSY
    images/test-bg.png: P7AVU44FYXZ7QLSL2JWBIH5PEGGESITZ
    images/tiktok.svg: PEEEPMLR7EYCBF7OTFLYW5M6QZGXRWJX
    images/twitter.svg: 2FRLS36U4XGO3P4HRJZLGFHGYIPZGE5C
    images/why-choose-image.png: KKRYN4ZFFPL66R52D547NKLS2WLH65KF
    images/why-icon-1.png: S5ACTCUV76CXLML2I347WO3QAOIB7U3E
    images/why-icon-2.png: WR2F4HEZZYC2EEBVN6OMS5DCXHUQ4OMT
    images/why-icon-3.png: X2LHBFV4I73DTQVUNE3JJ5DJ2GN5KCNQ
    images/why-icon-4.png: LBQT4CGVKDIBNTJ2D4VLNHMTS6IGAFCP
    images/youtube.svg: GPFA7UNKNJGURLLUHI3V7LEWVG3PHGSF
    standard-page.html: GT2NWDGVDYDV44S2MEYIOEENFQWBV2UZ
    theme.css: RHYABXL2K3AIWVFEXH54YE2IMVNT2HKJ
  forms:
    Account: '1742864997069842988599920.4894'
    Account.AddSignModal: '1743577240449956998388775.9501'
    Account.ItemTemplate1: '1743746113872639760009215.7578'
    Account.RowTemplate1: '1743746191736645806577552.3589'
    Account.SettingsModal: '1743743810527266610675918.709'
    Contact: '174286509525259111324095.750374'
    FAQs: '1744196822806375051359626.0291'
    Footer: '1743194036450572275722539.4131'
    Header: '1743193425023833297886320.0764'
    Home: '1743193573439959120102800.8041'
    Login: '1742865338635590336628316.67'
    Main: '1743192266618748086647295.0114'
    Pricing: '1742865398182456711748233.5588'
    PrivacyPolicy: '1744374144054407448349522.95575'
  modules: {}
  scripts: {}
  server_modules: {}
