color_scheme:
  colors:
  - {color: '#6abf4b', name: primary}
  - {color: '#fff', name: white}
  preset_groups: []
roles:
- {components: null, display_in_toolbox: false, name: account-page-btn}
- {components: null, display_in_toolbox: false, name: table}
- {components: null, display_in_toolbox: false, name: heading-h3}
- {name: main-heading}
